apiVersion: 1

datasources:
  - name: Kafka
    type: hamedkarbasi93-kafka-datasource
    isDefault: true
    access: proxy
    jsonData:
      kafkaVersion: "2.7.0"
      securityProtocol: PLAINTEXT
      bootstrapServers: kafka:9092
    editable: true
